name: hello world
on:
  push:
    path:
      - '!README.md'
      - '!docs/**'
      - '**.html' 
    branch:
      - 'main'
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello World, today is $TODAY
